// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserIndexImport } from './routes/user/index'
import { Route as ProjectIndexImport } from './routes/project/index'
import { Route as UserUserIdImport } from './routes/user/$userId'
import { Route as ProjectProjectIdImport } from './routes/project/$projectId'
import { Route as UserUserIdSettingsImport } from './routes/user/$userId.settings'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIndexRoute = UserIndexImport.update({
  path: '/user/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectIndexRoute = ProjectIndexImport.update({
  path: '/project/',
  getParentRoute: () => rootRoute,
} as any)

const UserUserIdRoute = UserUserIdImport.update({
  path: '/user/$userId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectIdRoute = ProjectProjectIdImport.update({
  path: '/project/$projectId',
  getParentRoute: () => rootRoute,
} as any)

const UserUserIdSettingsRoute = UserUserIdSettingsImport.update({
  path: '/settings',
  getParentRoute: () => UserUserIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectId': {
      preLoaderRoute: typeof ProjectProjectIdImport
      parentRoute: typeof rootRoute
    }
    '/user/$userId': {
      preLoaderRoute: typeof UserUserIdImport
      parentRoute: typeof rootRoute
    }
    '/project/': {
      preLoaderRoute: typeof ProjectIndexImport
      parentRoute: typeof rootRoute
    }
    '/user/': {
      preLoaderRoute: typeof UserIndexImport
      parentRoute: typeof rootRoute
    }
    '/user/$userId/settings': {
      preLoaderRoute: typeof UserUserIdSettingsImport
      parentRoute: typeof UserUserIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProjectProjectIdRoute,
  UserUserIdRoute.addChildren([UserUserIdSettingsRoute]),
  ProjectIndexRoute,
  UserIndexRoute,
])
