// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TeamTeamNameImport } from './routes/team/$teamName'
import { Route as TeamTeamNameProjectImport } from './routes/team/$teamName.project'
import { Route as TeamTeamNameProjectNameImport } from './routes/team/$teamName.$projectName'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamTeamNameRoute = TeamTeamNameImport.update({
  path: '/team/$teamName',
  getParentRoute: () => rootRoute,
} as any)

const TeamTeamNameProjectRoute = TeamTeamNameProjectImport.update({
  path: '/project',
  getParentRoute: () => TeamTeamNameRoute,
} as any)

const TeamTeamNameProjectNameRoute = TeamTeamNameProjectNameImport.update({
  path: '/$projectName',
  getParentRoute: () => TeamTeamNameRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/team/$teamName': {
      preLoaderRoute: typeof TeamTeamNameImport
      parentRoute: typeof rootRoute
    }
    '/team/$teamName/$projectName': {
      preLoaderRoute: typeof TeamTeamNameProjectNameImport
      parentRoute: typeof TeamTeamNameImport
    }
    '/team/$teamName/project': {
      preLoaderRoute: typeof TeamTeamNameProjectImport
      parentRoute: typeof TeamTeamNameImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  TeamTeamNameRoute.addChildren([
    TeamTeamNameProjectNameRoute,
    TeamTeamNameProjectRoute,
  ]),
])
