name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # specify the node version

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Run lint
        run: npm run lint
        working-directory: client

      - name: Run depcheck
        run: npm run depcheck
        working-directory: client

      - name: Run tsc
        run: npm run ts-check
        working-directory: client
